# Generated by Django 5.0.3 on 2024-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='bebida',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bebida',
            name='ingredientes_base',
            field=models.ManyToManyField(to='POSNAT.ingrediente'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DecoradorBebida',
        ),
    ]
