# Generated by Django 5.0.3 on 2024-04-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0002_remove_ingrediente_descripcion_bebida_detalles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bebida',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='POSNAT.categoria'),
        ),
    ]
