# Generated by Django 5.0.3 on 2024-04-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0004_tipo_rename_ingredientes_base_bebida_ingredientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POSNAT.venta'),
        ),
    ]
