# Generated by Django 5.0.3 on 2024-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0005_alter_cliente_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='imagen',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='imagen_url',
            field=models.CharField(default='https://example.com/default_image.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
