# Generated by Django 5.0.3 on 2024-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0006_remove_ingrediente_imagen_ingrediente_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='ingrediente/'),
        ),
    ]
