# Generated by Django 5.0.3 on 2024-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0008_alter_bebida_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(default='static\\images\\sin.jpg', upload_to='ingrediente/'),
        ),
    ]
