# Generated by Django 4.2.11 on 2024-05-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0010_alter_bebida_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='bebida',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POSNAT.cliente'),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(default='static/images/sin.jpg', upload_to='bebidas/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='imagen',
            field=models.ImageField(default='static/images/sin.jpg', upload_to='ingredientes/'),
        ),
        migrations.CreateModel(
            name='DetalleVentaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSNAT.detalleventa')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POSNAT.ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='ingredientes_extra',
            field=models.ManyToManyField(through='POSNAT.DetalleVentaIngrediente', to='POSNAT.ingrediente'),
        ),
    ]
