# Generated by Django 4.2.11 on 2024-05-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0011_remove_cliente_venta_remove_venta_bebida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='cantidad_extra',
            new_name='cantidad_porcion_extra',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='compañia',
            new_name='compañía',
        ),
        migrations.AddField(
            model_name='bebida',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad',
            field=models.CharField(default='gramos', max_length=50),
        ),
        migrations.AddField(
            model_name='reporteventa',
            name='cantidad_de_clientes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporteventa',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteventa',
            name='total_bebidas_vendidas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
