# Generated by Django 4.2.11 on 2024-05-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0013_alter_ingrediente_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebida',
            old_name='is_available',
            new_name='disponible',
        ),
    ]
