# Generated by Django 4.2.11 on 2024-05-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0015_alter_venta_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamañoBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_agua', models.PositiveIntegerField()),
                ('cantidad_leche', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cantidad_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidad_original',
            field=models.CharField(choices=[('litros', 'Litros'), ('kilogramos', 'Kilogramos')], default='kilogramos', max_length=10),
        ),
        migrations.AddField(
            model_name='bebida',
            name='tamaños',
            field=models.ManyToManyField(to='POSNAT.tamañobebida'),
        ),
    ]
