# Generated by Django 4.2.11 on 2024-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0016_tamañobebida_ingrediente_cantidad_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidad_original',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cantidad_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
