# Generated by Django 4.2.11 on 2024-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSNAT', '0017_remove_ingrediente_cantidad_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamañobebida',
            name='nombre',
            field=models.CharField(choices=[('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=50, unique=True),
        ),
    ]
